// ============================================
// K-POP KOSMIC - BRAND CONFIGURATION
// ============================================
// K-Pop themed branding
// Copy this file to config.js to activate
// ============================================

const BRAND_CONFIG = {
    // ============================================
    // BRAND IDENTITY
    // ============================================
    brandName: "K-pop Kosmic",
    tagline: "Your Idol Destiny Revealed",
    subTagline: "58 Readings • Complete Idol Blueprint • Your Cosmic K-pop Journey",
    
    // Who is this reading for?
    subjectType: "person",
    subjectLabel: "Stan",
    subjectLabelPlural: "Stans",
    
    // ============================================
    // COPY & LANGUAGE
    // ============================================
    inputLabels: {
        name: "Your Stage Name",
        namePlaceholder: "Enter your name (or dream stage name)",
        nameHelper: "The name that resonates with your idol energy",
        
        birthDate: "Date of Birth",
        birthDateHelper: "Your birthday (like your bias!)",
        
        birthTime: "Time of Birth",
        birthTimeHelper: "For accurate Rising Sign (check with your parents!)",
        
        birthPlace: "Place of Birth",
        birthPlacePlaceholder: "City, Country",
        birthPlaceHelper: "Where your idol journey began"
    },
    
    ctaButton: "✨ Reveal My Idol Destiny",
    loadingMessage: "Calculating your idol blueprint... 🎤",
    
    // Result page copy
    resultTitle: "Complete Idol Blueprint",
    resultSubtitle: "The Cosmic Profile of",
    generatedBy: "Generated by K-pop Kosmic (11:11)",
    
    // ============================================
    // SECTION NAMES - K-Pop Themed
    // ============================================
    sections: {
        celestial: {
            name: "Celestial Positions",
            icon: "🌟",
            description: "Your planetary influences and idol archetype energy"
        },
        numbers: {
            name: "Trainee Numbers",
            icon: "🔢",
            description: "The numerological blueprint of your idol journey"
        },
        soul: {
            name: "Debut Mission",
            icon: "✨",
            description: "Your deeper purpose and unique idol gifts"
        },
        forecasts: {
            name: "Comeback Seasons",
            icon: "🎤",
            description: "What the cosmos has in store for your career"
        },
        cycles: {
            name: "Era Cycles",
            icon: "💫",
            description: "Key phases in your idol evolution"
        }
    },
    
    // ============================================
    // READING TITLES - K-Pop Themed
    // ============================================
    readingTitles: {
        sunSign: "Sun Sign - Your Core Idol Energy",
        moonSign: "Moon Sign - Your Emotional Concept",
        risingSign: "Rising Sign - Your Stage Presence",
        mercurySign: "Mercury - Your Communication Style",
        venusSign: "Venus - Your Visual & Love Concept",
        marsSign: "Mars - Your Performance Energy",
        jupiterSign: "Jupiter - Your Growth & Luck",
        saturnSign: "Saturn - Your Trainee Lessons",
        chineseZodiac: "Chinese Zodiac - Your Animal Energy",
        moonPhase: "Birth Moon Phase - Your Debut Energy",
        
        lifePath: "Life Path - Your Idol Archetype",
        destiny: "Destiny Number - Your Debut Purpose",
        soulUrge: "Soul Urge - Your True Concept",
        personality: "Personality Number - Your Public Image",
        birthday: "Birthday Number - Your Special Talents",
        maturity: "Maturity Number - Your Senior Era",
        
        personalYear: "Current Era Energy",
        pinnacle: "Career Pinnacles - Major Comebacks",
        challenge: "Growth Challenges - Trainee Lessons",
        
        northNode: "North Node - Your Debut Direction",
        southNode: "South Node - Your Pre-Debut Gifts",
        lifeLesson: "Core Idol Lesson",
        
        yearAhead: "This Era's Forecast",
        firstYear: "Debut Year Energy"
    },
    
    // ============================================
    // COLORS & STYLING - Neon K-Pop Theme
    // ============================================
    colors: {
        primary: "#FF69B4",      // Hot pink
        secondary: "#9400D3",    // Purple
        accent: "#00FFFF",       // Cyan
        background: "#1a0a2e",   // Deep purple
        backgroundDark: "#0a0515",
        text: "#ffffff",
        textLight: "#ffffff",
        cardBg: "rgba(255,255,255,0.05)",
        cardBorder: "rgba(255,105,180,0.3)"
    },
    
    // ============================================
    // FONTS
    // ============================================
    fonts: {
        heading: "'Impact', 'Arial Black', sans-serif",
        body: "'Segoe UI', 'Helvetica Neue', sans-serif",
        accent: "'Impact', 'Arial Black', sans-serif"
    },
    
    // ============================================
    // THEME
    // ============================================
    theme: "dark",
    
    // ============================================
    // FEATURES
    // ============================================
    features: {
        showBirthTime: true,
        showBirthPlace: true,
        showPDFDownload: true,
        showShareButtons: true,
        showTableOfContents: true,
        showProgressBar: true,
        requireBirthTime: false,
        requireBirthPlace: false
    },
    
    // ============================================
    // SOCIAL SHARING
    // ============================================
    sharing: {
        hashtags: ["KpopKosmic", "IdolDestiny", "KpopNumerology", "StanLife", "1111"],
        defaultMessage: "I just discovered my idol destiny! 🎤✨ My archetype is...",
        twitterHandle: "@kpopkosmic"
    },
    
    // ============================================
    // PREMIUM FEATURES
    // ============================================
    premium: {
        enabled: false,
        price: "$11.11",
        features: [
            "PDF Download",
            "No Ads",
            "Printable Format",
            "Bias Compatibility"
        ]
    },
    
    // ============================================
    // FOOTER
    // ============================================
    footer: {
        copyright: "© 2025 K-pop Kosmic (11:11)",
        disclaimer: "For entertainment purposes only. Not affiliated with any K-pop agency or artist. Stan responsibly! 💜",
        links: [
            { text: "Privacy Policy", url: "/privacy.html" },
            { text: "Terms of Service", url: "/terms.html" },
            { text: "Contact", url: "/contact.html" }
        ]
    },
    
    // ============================================
    // SEO
    // ============================================
    seo: {
        title: "K-pop Kosmic - Discover Your Idol Destiny | K-Pop Numerology & Astrology",
        description: "Find your K-pop idol archetype with 58 personalized readings! Discover your stage presence, debut energy, and cosmic K-pop destiny. Free idol blueprint for stans.",
        keywords: "kpop numerology, kpop astrology, idol archetype, kpop personality test, stan destiny, kpop birth chart, idol energy, kpop kosmic"
    }
};

const BRAND_PRESETS = {
    kpop: BRAND_CONFIG
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { BRAND_CONFIG, BRAND_PRESETS };
}